CREATE TABLE `leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`phone` varchar(50) NOT NULL,
	`whatsapp` varchar(50),
	`email` varchar(320),
	`equipmentType` varchar(100),
	`component` varchar(100),
	`symptoms` text,
	`comment` text,
	`sourcePage` varchar(500) NOT NULL,
	`formType` varchar(50) NOT NULL,
	`ipAddress` varchar(45),
	`userAgent` text,
	`status` enum('new','contacted','qualified','converted','rejected') NOT NULL DEFAULT 'new',
	`emailSent` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leads_id` PRIMARY KEY(`id`)
);
